# Generated by Django 2.2.16 on 2021-09-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.IntegerField(primary_key=True, serialize=False)),
                ('album_name', models.TextField()),
                ('album_status', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'public"."album',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Firtu',
            fields=[
                ('firtu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('firtu_title', models.TextField()),
                ('firtu_date', models.DateField()),
                ('firtu_desc', models.TextField()),
                ('firtu_img', models.TextField()),
                ('firtu_status', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'public"."firtu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gallery_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gallery_name', models.TextField()),
                ('gallery_img', models.TextField()),
                ('gallery_date', models.DateField()),
                ('gallery_status', models.CharField(default='link', max_length=20)),
                ('gallery_link', models.TextField()),
                ('gallery_log', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'public"."gallery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mastercategory',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('categorys', models.TextField()),
                ('category_status', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'master"."mastercategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mastermenu',
            fields=[
                ('menu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('menu', models.TextField()),
                ('parent_id', models.IntegerField()),
                ('status', models.TextField()),
                ('level', models.CharField(default='A', max_length=1)),
                ('url', models.TextField()),
                ('icon', models.TextField()),
            ],
            options={
                'db_table': 'master"."mastermenu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Masteruser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('full_name', models.TextField()),
                ('level_user', models.CharField(default='admin', max_length=20)),
                ('user_status', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'master"."masteruser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postsberitaslider',
            fields=[
                ('posts_id', models.IntegerField(primary_key=True, serialize=False)),
                ('posts_date', models.DateField()),
                ('posts_title', models.TextField()),
                ('posts_desc', models.TextField()),
                ('posts_img', models.TextField()),
                ('menu_id', models.IntegerField()),
                ('posts_status', models.CharField(default='publish', max_length=20)),
                ('posts_page_view', models.IntegerField()),
                ('posts_keyword', models.TextField()),
            ],
            options={
                'db_table': 'public"."posts',
                'managed': False,
            },
        ),
    ]
