# Generated by Django 2.2.16 on 2021-08-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mastercategory',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.TextField()),
            ],
        ),
    ]
