# Generated by Django 2.2.16 on 2021-09-10 14:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemarapapua_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mastermenu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu', models.TextField()),
                ('parent_id', models.IntegerField()),
                ('status', models.CharField(default='aktif', max_length=5)),
                ('level', models.CharField(default='A', max_length=1)),
                ('url', models.TextField()),
                ('icon', models.TextField()),
            ],
            options={
                'db_table': 'master"."mastermenu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Masteruser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('full_name', models.TextField()),
                ('level_user', models.TextField(default='superadmin', max_length=20)),
                ('user_status', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'master"."masteruser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postsberita',
            fields=[
                ('posts_id', models.IntegerField(primary_key=True, serialize=False)),
                ('posts_date', models.DateField()),
                ('posts_title', models.TextField()),
                ('posts_desc', ckeditor.fields.RichTextField()),
                ('posts_img', models.TextField()),
                ('menu_id', models.IntegerField()),
                ('posts_status', models.CharField(default='publish', max_length=20)),
                ('posts_page_view', models.IntegerField()),
                ('posts_keyword', models.TextField()),
            ],
            options={
                'db_table': 'public"."posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postsfirmantuhan',
            fields=[
                ('firtu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('firtu_title', models.TextField()),
                ('firtu_date', models.DateField()),
                ('firtu_desc', models.TextField()),
                ('firtu_img', models.TextField()),
                ('firtu_status', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'public"."firtu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Setting_aplikasi',
            fields=[
                ('setting_id', models.IntegerField(primary_key=True, serialize=False)),
                ('setting_nohp', models.TextField()),
                ('setting_addres', models.TextField()),
                ('setting_about_title', models.TextField()),
                ('setting_about_organisasi', models.TextField()),
                ('setting_email', models.TextField()),
                ('setting_desc_app', models.TextField()),
            ],
            options={
                'db_table': 'master"."setting_aplikasi',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='mastercategory',
            options={'managed': False},
        ),
    ]
