# Generated by Django 2.2.16 on 2021-09-11 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cemarapapua_app', '0002_auto_20210910_2357'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mastercategory',
            table='master"."mastercategory',
        ),
    ]
